# Jekyll Defaults
title: djKooks
description: Dennis Jung's blog
baseurl: "" # the subpath of your site, e.g. /blog

url: "djkooks.github.io"
github: http://github.com/djKooks
highlighter: rouge
markdown: kramdown
permalink: /post/:title/
paginate: 4
gems: [jekyll-paginate]
paginate_path: "/page:num"
rss_path: /feed.xml
navigation:
- text: About
  url: /about/
- text: Archives
  url: /archives/
- text: Tags
  url: /tags/
